/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MEVBotGame {
      
    export type BotScoreStruct = {botOwner: AddressLike, botName: string, score: BigNumberish}

    export type BotScoreStructOutput = [botOwner: string, botName: string, score: bigint] & {botOwner: string, botName: string, score: bigint }
  
    }

  export interface MEVBotGameInterface extends Interface {
    getFunction(nameOrSignature: "MAX_ROUND_DURATION" | "MIN_BOTS_PER_ROUND" | "TOP_BOTS_REWARDED" | "botScores" | "bots" | "deactivateBot" | "distributeRewards" | "endRound" | "gameTreasury" | "getContractBalance" | "getPlayerBots" | "getRoundLeaders" | "getRoundStatus" | "isBotActive" | "owner" | "playerBots" | "registerBot" | "renounceOwnership" | "roundParticipants" | "roundTopBots" | "roundWinnerCount" | "rounds" | "startRound" | "submitAttempt" | "totalBots" | "totalRounds" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BotRegistered" | "OwnershipTransferred" | "RewardDistributed" | "RoundEnded" | "RoundStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_ROUND_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_BOTS_PER_ROUND', values?: undefined): string;
encodeFunctionData(functionFragment: 'TOP_BOTS_REWARDED', values?: undefined): string;
encodeFunctionData(functionFragment: 'botScores', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'bots', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deactivateBot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'distributeRewards', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'endRound', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'gameTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'getContractBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPlayerBots', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoundLeaders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoundStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isBotActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'playerBots', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerBot', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'roundParticipants', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'roundTopBots', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'roundWinnerCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rounds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'startRound', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitAttempt', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalBots', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRounds', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_ROUND_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_BOTS_PER_ROUND', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TOP_BOTS_REWARDED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'botScores', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateBot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gameTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContractBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlayerBots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoundLeaders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoundStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBotActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playerBots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerBot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roundParticipants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roundTopBots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roundWinnerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rounds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitAttempt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRounds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace BotRegisteredEvent {
      export type InputTuple = [botId: BigNumberish, owner: AddressLike, name: string, strategy: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [botId: bigint, owner: string, name: string, strategy: bigint, timestamp: bigint];
      export interface OutputObject {botId: bigint, owner: string, name: string, strategy: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardDistributedEvent {
      export type InputTuple = [roundId: BigNumberish, winner: AddressLike, amount: BigNumberish, position: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [roundId: bigint, winner: string, amount: bigint, position: bigint, timestamp: bigint];
      export interface OutputObject {roundId: bigint, winner: string, amount: bigint, position: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundEndedEvent {
      export type InputTuple = [roundId: BigNumberish, endTime: BigNumberish, winnerCount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [roundId: bigint, endTime: bigint, winnerCount: bigint, timestamp: bigint];
      export interface OutputObject {roundId: bigint, endTime: bigint, winnerCount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundStartedEvent {
      export type InputTuple = [roundId: BigNumberish, startTime: BigNumberish, endTime: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [roundId: bigint, startTime: bigint, endTime: bigint, timestamp: bigint];
      export interface OutputObject {roundId: bigint, startTime: bigint, endTime: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MEVBotGame extends BaseContract {
    
    connect(runner?: ContractRunner | null): MEVBotGame;
    waitForDeployment(): Promise<this>;

    interface: MEVBotGameInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_ROUND_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_BOTS_PER_ROUND: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TOP_BOTS_REWARDED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    botScores: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    bots: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, boolean] & {owner: string, name: string, strategy: bigint, registeredAt: bigint, active: boolean }],
      'view'
    >
    

    
    deactivateBot: TypedContractMethod<
      [botId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    distributeRewards: TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    endRound: TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    gameTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getContractBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPlayerBots: TypedContractMethod<
      [player: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getRoundLeaders: TypedContractMethod<
      [roundId: BigNumberish, ],
      [MEVBotGame.BotScoreStructOutput[]],
      'view'
    >
    

    
    getRoundStatus: TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    isBotActive: TypedContractMethod<
      [botId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    playerBots: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    registerBot: TypedContractMethod<
      [name: string, strategy: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    roundParticipants: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    roundTopBots: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, bigint] & {botOwner: string, botName: string, score: bigint }],
      'view'
    >
    

    
    roundWinnerCount: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    rounds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {id: bigint, startTime: bigint, endTime: bigint, status: bigint }],
      'view'
    >
    

    
    startRound: TypedContractMethod<
      [duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    submitAttempt: TypedContractMethod<
      [roundId: BigNumberish, botId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    totalBots: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRounds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_ROUND_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_BOTS_PER_ROUND'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TOP_BOTS_REWARDED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'botScores'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bots'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, boolean] & {owner: string, name: string, strategy: bigint, registeredAt: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'deactivateBot'): TypedContractMethod<
      [botId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeRewards'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endRound'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'gameTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getContractBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPlayerBots'): TypedContractMethod<
      [player: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRoundLeaders'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [MEVBotGame.BotScoreStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRoundStatus'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isBotActive'): TypedContractMethod<
      [botId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'playerBots'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerBot'): TypedContractMethod<
      [name: string, strategy: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'roundParticipants'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'roundTopBots'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, bigint] & {botOwner: string, botName: string, score: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'roundWinnerCount'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rounds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {id: bigint, startTime: bigint, endTime: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'startRound'): TypedContractMethod<
      [duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitAttempt'): TypedContractMethod<
      [roundId: BigNumberish, botId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'totalBots'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRounds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BotRegistered'): TypedContractEvent<BotRegisteredEvent.InputTuple, BotRegisteredEvent.OutputTuple, BotRegisteredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RewardDistributed'): TypedContractEvent<RewardDistributedEvent.InputTuple, RewardDistributedEvent.OutputTuple, RewardDistributedEvent.OutputObject>;
getEvent(key: 'RoundEnded'): TypedContractEvent<RoundEndedEvent.InputTuple, RoundEndedEvent.OutputTuple, RoundEndedEvent.OutputObject>;
getEvent(key: 'RoundStarted'): TypedContractEvent<RoundStartedEvent.InputTuple, RoundStartedEvent.OutputTuple, RoundStartedEvent.OutputObject>;

    filters: {
      
      'BotRegistered(uint256,address,string,uint8,uint256)': TypedContractEvent<BotRegisteredEvent.InputTuple, BotRegisteredEvent.OutputTuple, BotRegisteredEvent.OutputObject>;
      BotRegistered: TypedContractEvent<BotRegisteredEvent.InputTuple, BotRegisteredEvent.OutputTuple, BotRegisteredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RewardDistributed(uint256,address,uint256,uint256,uint256)': TypedContractEvent<RewardDistributedEvent.InputTuple, RewardDistributedEvent.OutputTuple, RewardDistributedEvent.OutputObject>;
      RewardDistributed: TypedContractEvent<RewardDistributedEvent.InputTuple, RewardDistributedEvent.OutputTuple, RewardDistributedEvent.OutputObject>;
    

      'RoundEnded(uint256,uint256,uint256,uint256)': TypedContractEvent<RoundEndedEvent.InputTuple, RoundEndedEvent.OutputTuple, RoundEndedEvent.OutputObject>;
      RoundEnded: TypedContractEvent<RoundEndedEvent.InputTuple, RoundEndedEvent.OutputTuple, RoundEndedEvent.OutputObject>;
    

      'RoundStarted(uint256,uint256,uint256,uint256)': TypedContractEvent<RoundStartedEvent.InputTuple, RoundStartedEvent.OutputTuple, RoundStartedEvent.OutputObject>;
      RoundStarted: TypedContractEvent<RoundStartedEvent.InputTuple, RoundStartedEvent.OutputTuple, RoundStartedEvent.OutputObject>;
    
    };
  }